# Generated by Django 5.0.6 on 2024-09-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_password_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Earth', max_length=200, null=True),
        ),
    ]
