# Generated by Django 5.0.6 on 2024-10-21 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trade',
            table='trade_transaction',
        ),
    ]
